실습과제
1. 제공 되는 'Floating_Population_2004.csv' 파일을 파이썬 파일 처리 읽기 기능을 이용하여 읽어온 후 NumPy 배열로 생성하고 NumPy가 제공하는 함수를 활용하여 데이터를 분석한 스크립트를 제출한다.

# 서울시 유동인구 분석

## 0. NumPy import

In [1]:
import numpy as np

## 1. 파일 내용 저장 파이썬 리스트 변수 선언

In [2]:
# data 저장 list
date_list = []
time_list = []
age_list = []
gender_list = []
gu_list = []
population_list = []

## 2. 파일에서 전체 데이터 읽어서 데이터 확인( 'Floating_Population_2004.csv.csv )

In [ ]:
with open( 'Floating_Population_2004.csv', 'r', encoding = 'utf-8' ) as f:
    line = f.readline()
    while line:
        print( line )
        line = f.readline()

## 3. 파일에서 전체 필요 데이터 읽어서 list에 저장( 'Floating_Population_2004.csv.csv )

In [5]:
with open( 'Floating_Population_2004.csv', 'r', encoding = 'utf-8' ) as f:
    line = f.readline() # 제목줄 제거
    line = f.readline()
    while line:
        data = line.split( ',' )
        
        # 날짜 list에 추가
        date_temp = data[ 0 ].split( '"' )
        date_list.append( date_temp[ 1 ] )
        
        # 시간 list에 추가
        time_temp = data[ 1 ].split( '"')
        time_list.append( time_temp[ 1 ] )
        
        # 연령 list에 추가
        age_temp = data[ 2 ].split( '"' )
        age_list.append( age_temp[ 1 ] )
        
        # 성별 list에 추가
        gender_temp = data[ 3 ].split( '"' )
        gender_list.append( gender_temp[ 1 ] )
        
        # 구 list에 추가
        gu_temp = data[ 5 ].split( '"' )
        gu_list.append( gu_temp[ 1 ] )
        
        # 유동인구 list에 추가
        population_temp = data[ 6 ].split( '"' )
        population_list.append( int( population_temp[ 1 ] ) )
        
        line = f.readline()

## 4. 읽은 데이터 확인( 처음 5개, 마지막 5개 )

In [6]:
date_list[ :5 ], date_list[ len( date_list ) - 5 : ]

(['20200401', '20200401', '20200401', '20200401', '20200401'],
 ['20200430', '20200430', '20200430', '20200430', '20200430'])

In [7]:
time_list[ :5 ], time_list[ len( time_list ) - 5 : ]

(['00', '00', '00', '00', '01'], ['22', '22', '23', '23', '23'])

In [8]:
age_list[ :5 ], age_list[ len( age_list ) - 5 : ]

(['20', '20', '30', '50', '30'], ['40', '50', '20', '30', '40'])

In [9]:
gender_list[ :5 ], gender_list[ len( gender_list ) - 5: ]

(['남성', '남성', '여성', '남성', '여성'], ['여성', '여성', '여성', '여성', '남성'])

In [10]:
gu_list[ :5 ], gu_list[ len( gu_list ) - 5: ]

(['도봉구', '도봉구', '동대문구', '구로구', '강남구'], ['성동구', '서대문구', '용산구', '서대문구', '강남구'])

In [11]:
population_list[ :5 ], population_list[ len( population_list ) - 5: ]

([21490, 21490, 27260, 35670, 52380], [22150, 23270, 18570, 21100, 45730])

## 5. NumPy 배열 생성

### 5.1 전체 날짜/시간

In [12]:
date_array = np.array( date_list )
date_array[ :10 ], date_array[ date_array.size - 10: ]

(array(['20200401', '20200401', '20200401', '20200401', '20200401',
        '20200401', '20200401', '20200401', '20200401', '20200401'],
       dtype='<U8'),
 array(['20200430', '20200430', '20200430', '20200430', '20200430',
        '20200430', '20200430', '20200430', '20200430', '20200430'],
       dtype='<U8'))

In [13]:
date_array.ndim, date_array.shape, date_array.size, date_array.dtype

(1, (216001,), 216001, dtype('<U8'))

In [14]:
time_array = np.array( time_list )
time_array[ :10 ], time_array[ time_array.size - 10: ]

(array(['00', '00', '00', '00', '01', '01', '02', '02', '02', '03'],
       dtype='<U2'),
 array(['21', '22', '22', '22', '22', '22', '22', '23', '23', '23'],
       dtype='<U2'))

In [15]:
time_array.ndim, time_array.shape, time_array.size, time_array.dtype

(1, (216001,), 216001, dtype('<U2'))

### 5.2 전체 연령대

In [16]:
age_array = np.array( age_list )
age_array[ :10 ], age_array[ age_array.size - 10 : ]

(array(['20', '20', '30', '50', '30', '40', '20', '30', '50', '20'],
       dtype='<U2'),
 array(['70', '20', '20', '40', '40', '40', '50', '20', '30', '40'],
       dtype='<U2'))

In [17]:
age_array.ndim, age_array.shape, age_array.size, age_array.dtype

(1, (216001,), 216001, dtype('<U2'))

### 5.3 전체 성별

In [18]:
gender_array = np.array( gender_list )
gender_array[ :10 ], gender_array[ gender_array.size - 10: ]

(array(['남성', '남성', '여성', '남성', '여성', '남성', '남성', '남성', '여성', '남성'],
       dtype='<U2'),
 array(['남성', '남성', '여성', '여성', '여성', '여성', '여성', '여성', '여성', '남성'],
       dtype='<U2'))

In [19]:
gender_array.ndim, gender_array.shape, gender_array.size, gender_array.dtype

(1, (216001,), 216001, dtype('<U2'))

### 5.4 전체 구

In [20]:
gu_array = np.array( gu_list )
gu_array[ :10 ], gu_array[ gu_array.size - 10: ]

(array(['도봉구', '도봉구', '동대문구', '구로구', '강남구', '동대문구', '성동구', '강서구', '성동구',
        '성동구'], dtype='<U4'),
 array(['중랑구', '강동구', '도봉구', '도봉구', '마포구', '성동구', '서대문구', '용산구', '서대문구',
        '강남구'], dtype='<U4'))

In [21]:
gu_array.ndim, gu_array.shape, gu_array.size, gu_array.dtype

(1, (216001,), 216001, dtype('<U4'))

### 5.5 전체 유동 인구수

In [22]:
population_array = np.array( population_list )
population_array[ :10 ], population_array[ population_array.size - 10: ]

(array([21490, 21490, 27260, 35670, 52380, 28420, 23930, 51720, 23550,
        24070]),
 array([13230, 28390, 19670, 26320, 29860, 22150, 23270, 18570, 21100,
        45730]))

In [23]:
population_array.ndim, population_array.shape, population_array.size, population_array.dtype

(1, (216001,), 216001, dtype('int32'))

## 6. 데이터에 대한 통계 / 집계 출력

### 6.0 날짜, 시간, 성별, 연령대 목록 생성( 중복 data 배제 방법 )

In [24]:
# 전체 날짜 목록 생성
date_unique = np.unique( date_array )
print( '데이터 수집일 : {}'.format( date_unique[ : ] ) )

데이터 수집일 : ['20200401' '20200402' '20200403' '20200404' '20200405' '20200406'
 '20200407' '20200408' '20200409' '20200410' '20200411' '20200412'
 '20200413' '20200414' '20200415' '20200416' '20200417' '20200418'
 '20200419' '20200420' '20200421' '20200422' '20200423' '20200424'
 '20200425' '20200426' '20200427' '20200428' '20200429' '20200430']


In [25]:
print( '데이터 수집 일수 : {}일'.format( date_unique.size ) )

데이터 수집 일수 : 30일


In [26]:
# 전체 시간 목록 생성
time_unique = np.unique( time_array )
print( '데이터 수집 시간대 : {}'.format( time_unique[ : ] ) )

데이터 수집 시간대 : ['00' '01' '02' '03' '04' '05' '06' '07' '08' '09' '10' '11' '12' '13'
 '14' '15' '16' '17' '18' '19' '20' '21' '22' '23']


In [27]:
# 전체 성별 목록 생성
gender_unique = np.unique( gender_array )
print( '데이터 수집 성별 : {}'.format( gender_unique ) )

데이터 수집 성별 : ['남성' '여성']


In [28]:
age_unique = np.unique( age_array )
print( '데이터 수집 연령대 : {}'.format( age_unique ) )

데이터 수집 연령대 : ['20' '30' '40' '50' '60' '70']


In [40]:
gu_unique = np.unique( gu_array )
print( '데이터 수집 구 : {}'.format( gu_unique ) )
print( '데이터 수집 구의 수 : {}개구'.format( gu_unique.size ) )

데이터 수집 구 : ['강남구' '강동구' '강북구' '강서구' '관악구' '광진구' '구로구' '금천구' '노원구' '도봉구' '동대문구' '동작구'
 '마포구' '서대문구' '서초구' '성동구' '성북구' '송파구' '양천구' '영등포구' '용산구' '은평구' '종로구' '중구'
 '중랑구']
데이터 수집 구의 수 : 25개구


### 6.1 전체 데이터 수

In [31]:
print( '총 data 수 : {}건'.format( date_array.size ) )

총 data 수 : 216001건


### 6.2 전체 유동 인구수

In [32]:
print( '총 유동인구 수 : {}명'.format( population_array.sum() ) )

총 유동인구 수 : 1594891734명


### 6.3 전체 유동 인구에 대한 평균 및 1사분위, 중앙값, 3사 분위수

In [33]:
print( '평균 유동인구 수           : {:8.2f}명'.format( population_array.mean() ) )
print( "유동 인구에 대한 1사분위수 : {:8.2f}명".format( np.percentile( population_array, 25 ) ) )
print( "유동 인구에 대한 중앙값    : {:8.2f}명".format( np.median( population_array ) ) )
print( "유동 인구에 대한 3사분위수 : {:8.2f}명".format( np.percentile( population_array, 75 ) ) )

평균 유동인구 수           : 27267.74명
유동 인구에 대한 1사분위수 : 18070.00명
유동 인구에 대한 중앙값    : 25470.00명
유동 인구에 대한 3사분위수 : 34090.00명


### 6.4 유동 인구에 대한 분산 및 표준편차

In [34]:
print( '유동 인구에 대한 분산 : {:.2f}'.format( population_array.var() ) )
print( '유동 인구에 대한 표준편차 : {:.2f}'.format( population_array.std() ) )

유동 인구에 대한 분산 : 155759756.14
유동 인구에 대한 표준편차 : 12480.37


### 6.5 유동 인구수가 가장 적은 날과 많은 날

In [35]:
index = population_array.argmin()
print( '유동 인구수가 적은 날 : {}-{} {}대 {} {} {}'.format( date_array[ index ], time_array[ index ],
                                                             age_array[ index ], 
                                                             gender_array[ index ],
                                                             gu_array[ index ],
                                                             population_array[ index ] ) )
index = population_array.argmax()
print( '유동 인구수가 많은 날 : {}-{} {}대 {} {} {}'.format( date_array[ index ], time_array[ index ],
                                                       age_array[ index ], 
                                                       gender_array[ index ],
                                                       gu_array[ index ],
                                                       population_array[ index ] ) )

유동 인구수가 적은 날 : 20200426-03 70대 남성 중구 4380
유동 인구수가 많은 날 : 20200428-14 30대 여성 강남구 120640


### 6.6 강남구 유동 인구 분석

In [55]:
# 강남구 인덱스 추출
indexs = np.where( gu_unique[ 0 ] == gu_array )
indexs = indexs[ 0 ]
indexs

array([     4,     13,     41, ..., 215933, 215956, 216000], dtype=int64)

In [56]:
print( '{} 전체 유동 인구수 : {:10d}명'.format( gu_unique[ 0 ], population_array[ indexs ].sum() ) )
print( '{} 평균 유동 인구수 : {:10.2f}명'.format( gu_unique[ 0 ], population_array[ indexs ].mean() ) )

강남구 전체 유동 인구수 :  415479300명
강남구 평균 유동 인구수 :   48087.88명


In [57]:
# 강남구 index 추출
total = 0
print( '{} 일자별 유동 인구 :'.format( gu_unique[ 0 ] ) )
for index in indexs:
    print( '{}-{} : {} {}명'.format( date_array[ index ], time_array[ index ], 
                                     gender_array[ index ], population_array[ index ] ) )

강남구 일자별 유동 인구 :
20200401-01 : 여성 52380명
20200401-04 : 남성 40510명
20200401-12 : 남성 18640명
20200401-14 : 여성 59710명
20200401-20 : 여성 59900명
20200403-02 : 여성 28170명
20200403-07 : 여성 32960명
20200403-21 : 남성 49640명
20200403-21 : 남성 26640명
20200404-03 : 여성 50880명
20200404-16 : 남성 15420명
20200405-16 : 남성 46850명
20200406-14 : 남성 67740명
20200407-00 : 남성 50850명
20200407-09 : 여성 78820명
20200408-00 : 여성 19390명
20200408-21 : 여성 19750명
20200409-02 : 남성 40730명
20200409-13 : 여성 100760명
20200409-16 : 여성 112630명
20200410-07 : 남성 67790명
20200410-15 : 남성 100570명
20200410-16 : 남성 63650명
20200411-07 : 남성 43460명
20200411-17 : 남성 61760명
20200411-19 : 남성 50460명
20200413-04 : 여성 39110명
20200414-08 : 여성 51590명
20200414-10 : 남성 111600명
20200415-11 : 여성 62570명
20200415-15 : 남성 15340명
20200415-17 : 여성 28830명
20200415-18 : 여성 56460명
20200416-02 : 여성 50100명
20200416-19 : 여성 75470명
20200417-02 : 여성 27910명
20200417-20 : 여성 29370명
20200418-01 : 남성 41200명
20200418-03 : 남성 37590명
20200419-05 : 남성 44350명
20200419-10 : 여성 191

20200426-13 : 여성 55020명
20200426-14 : 여성 59440명
20200426-15 : 여성 54310명
20200426-19 : 남성 24220명
20200426-22 : 남성 47650명
20200426-23 : 여성 40160명
20200426-23 : 남성 24400명
20200427-00 : 남성 36850명
20200427-03 : 남성 14430명
20200427-11 : 남성 106310명
20200427-15 : 남성 119400명
20200427-16 : 여성 83360명
20200428-02 : 여성 51480명
20200428-22 : 여성 28720명
20200429-10 : 남성 19050명
20200429-19 : 여성 49620명
20200429-23 : 남성 55520명
20200430-00 : 남성 15120명
20200430-23 : 여성 26770명
20200401-01 : 여성 52870명
20200401-08 : 남성 32710명
20200401-08 : 여성 22590명
20200401-22 : 여성 19680명
20200402-02 : 남성 36750명
20200402-21 : 남성 26360명
20200402-22 : 남성 15270명
20200403-07 : 여성 48560명
20200404-14 : 여성 59870명
20200404-16 : 남성 52140명
20200405-00 : 여성 26830명
20200405-11 : 여성 18950명
20200405-12 : 남성 48910명
20200405-13 : 여성 51920명
20200405-14 : 여성 52880명
20200406-03 : 남성 36240명
20200406-10 : 여성 81040명
20200407-04 : 남성 24340명
20200407-10 : 남성 63730명
20200407-20 : 남성 50220명
20200408-00 : 남성 50110명
20200408-20 : 여성 29750명
20200409-07 : 

20200401-21 : 여성 52520명
20200402-13 : 여성 38260명
20200402-21 : 여성 29190명
20200402-23 : 여성 19450명
20200403-01 : 여성 51850명
20200403-03 : 남성 14660명
20200403-08 : 남성 60760명
20200403-20 : 남성 48740명
20200404-03 : 여성 40600명
20200404-14 : 남성 52140명
20200404-16 : 남성 44480명
20200404-18 : 여성 58930명
20200405-01 : 남성 38190명
20200405-07 : 남성 37350명
20200405-17 : 남성 49480명
20200405-20 : 여성 42550명
20200406-04 : 여성 49910명
20200406-06 : 남성 54260명
20200406-10 : 여성 38400명
20200407-04 : 여성 50830명
20200407-16 : 여성 21850명
20200408-05 : 여성 19940명
20200408-06 : 남성 37080명
20200408-11 : 남성 34170명
20200409-00 : 남성 37310명
20200409-05 : 여성 39780명
20200409-05 : 남성 46170명
20200409-08 : 남성 17850명
20200409-23 : 남성 51570명
20200410-00 : 여성 42620명
20200410-03 : 여성 50940명
20200410-08 : 여성 22660명
20200410-11 : 남성 34020명
20200410-13 : 남성 34170명
20200411-11 : 여성 61560명
20200411-15 : 남성 54110명
20200411-18 : 남성 41360명
20200412-02 : 여성 50310명
20200412-06 : 여성 40800명
20200412-06 : 남성 14350명
20200412-10 : 남성 48270명
20200412-19 : 남성

20200405-10 : 여성 46690명
20200405-23 : 여성 51940명
20200405-23 : 여성 18990명
20200406-00 : 여성 18990명
20200406-10 : 남성 68800명
20200406-13 : 여성 59500명
20200407-23 : 여성 42780명
20200408-11 : 여성 82960명
20200408-22 : 남성 43500명
20200409-13 : 남성 18700명
20200409-19 : 남성 27450명
20200409-22 : 여성 54610명
20200410-16 : 여성 57030명
20200410-22 : 남성 44640명
20200411-04 : 남성 45720명
20200411-10 : 남성 27640명
20200411-10 : 여성 20290명
20200411-18 : 여성 60750명
20200412-05 : 남성 14260명
20200412-07 : 남성 23870명
20200412-15 : 여성 27360명
20200412-20 : 남성 50730명
20200413-02 : 여성 49740명
20200413-04 : 남성 44390명
20200413-04 : 여성 51270명
20200413-08 : 여성 34940명
20200413-18 : 여성 31430명
20200414-01 : 남성 48260명
20200414-05 : 여성 39340명
20200414-12 : 남성 114900명
20200415-01 : 남성 48910명
20200415-01 : 남성 40890명
20200416-00 : 남성 36840명
20200416-01 : 남성 14710명
20200417-09 : 여성 77750명
20200417-11 : 남성 113280명
20200417-21 : 여성 28490명
20200417-23 : 남성 42870명
20200418-02 : 남성 47440명
20200418-09 : 여성 63280명
20200419-06 : 남성 23690명
20200420-01 : 

In [58]:
# 중구 인덱스 추출
indexs = np.where( gu_unique[ 23 ] == gu_array )
indexs = indexs[ 0 ]
indexs

array([    37,    189,    258, ..., 215896, 215916, 215983], dtype=int64)

In [59]:
print( '{} 전체 유동 인구수 : {:10d}명'.format( gu_unique[ 23 ], population_array[ indexs ].sum() ) )
print( '{} 평균 유동 인구수 : {:10.2f}명'.format( gu_unique[ 23 ], population_array[ indexs ].mean() ) )

중구 전체 유동 인구수 :  152646440명
중구 평균 유동 인구수 :   17667.41명


In [61]:
# 강남구 index 추출
total = 0
print( '{} 일자별 유동 인구 :'.format( gu_unique[ 23 ] ) )
for index in indexs:
    print( '{}-{} : {} {}명'.format( date_array[ index ], time_array[ index ], 
                                     gender_array[ index ], population_array[ index ] ) )

중구 일자별 유동 인구 :
20200401-10 : 여성 16490명
20200403-13 : 남성 55180명
20200404-16 : 여성 15070명
20200404-21 : 여성 7310명
20200405-05 : 여성 10360명
20200405-20 : 남성 4760명
20200406-02 : 남성 11080명
20200406-16 : 남성 54180명
20200408-05 : 여성 10460명
20200408-08 : 여성 13380명
20200408-19 : 남성 22830명
20200408-19 : 남성 10450명
20200409-16 : 여성 36930명
20200410-07 : 남성 26550명
20200410-10 : 여성 31530명
20200410-11 : 여성 33220명
20200410-12 : 남성 56910명
20200411-01 : 남성 14480명
20200411-04 : 남성 7090명
20200411-16 : 여성 19730명
20200412-05 : 여성 6710명
20200412-09 : 남성 11970명
20200413-00 : 여성 11000명
20200413-10 : 여성 32230명
20200414-02 : 남성 11190명
20200414-04 : 남성 10710명
20200414-20 : 여성 9320명
20200414-22 : 여성 12940명
20200415-06 : 남성 12660명
20200415-20 : 여성 13680명
20200416-04 : 여성 11430명
20200416-05 : 남성 12180명
20200416-07 : 남성 13980명
20200417-01 : 여성 11510명
20200417-05 : 남성 8320명
20200417-13 : 남성 52440명
20200417-16 : 남성 49970명
20200417-22 : 여성 13870명
20200418-10 : 남성 7040명
20200418-16 : 남성 17770명
20200419-15 : 여성 16350명
20200419

20200429-01 : 남성 4770명
20200429-02 : 여성 8000명
20200429-14 : 남성 60010명
20200429-17 : 남성 23930명
20200430-02 : 여성 12390명
20200430-10 : 남성 18050명
20200430-10 : 여성 11740명
20200430-11 : 남성 19520명
20200401-01 : 여성 7970명
20200401-03 : 여성 7860명
20200401-08 : 남성 37350명
20200401-13 : 여성 10700명
20200401-14 : 남성 23790명
20200402-14 : 여성 33330명
20200402-17 : 여성 38630명
20200402-18 : 남성 36250명
20200402-22 : 여성 12370명
20200403-05 : 남성 13430명
20200404-06 : 여성 10570명
20200404-13 : 여성 18480명
20200404-20 : 여성 7680명
20200405-06 : 여성 9330명
20200405-07 : 여성 7180명
20200405-10 : 여성 12910명
20200405-13 : 여성 15610명
20200406-00 : 남성 6920명
20200406-04 : 여성 10330명
20200406-16 : 남성 43680명
20200406-16 : 남성 8470명
20200406-18 : 남성 29060명
20200406-21 : 여성 8840명
20200406-23 : 여성 8260명
20200407-10 : 남성 54300명
20200407-11 : 남성 53170명
20200407-15 : 여성 34480명
20200407-15 : 남성 54560명
20200407-23 : 여성 12010명
20200408-07 : 남성 27270명
20200408-09 : 여성 9860명
20200408-11 : 여성 10860명
20200408-13 : 남성 54380명
20200408-22 : 여성 12820명
2020

20200409-04 : 남성 12230명
20200409-18 : 여성 23370명
20200409-23 : 여성 8090명
20200410-16 : 남성 53590명
20200410-22 : 여성 14010명
20200411-04 : 여성 11230명
20200411-07 : 여성 12210명
20200411-15 : 여성 8490명
20200412-11 : 여성 8480명
20200412-17 : 여성 14780명
20200412-23 : 여성 11200명
20200413-01 : 여성 10880명
20200413-09 : 남성 8610명
20200413-22 : 남성 13050명
20200414-11 : 여성 17400명
20200414-17 : 여성 33840명
20200414-21 : 남성 20450명
20200415-05 : 남성 10360명
20200415-09 : 여성 8050명
20200417-02 : 여성 10900명
20200418-12 : 남성 20840명
20200419-20 : 여성 12270명
20200420-08 : 여성 27940명
20200420-15 : 남성 55590명
20200421-04 : 여성 10770명
20200421-16 : 남성 58420명
20200421-23 : 여성 8200명
20200422-16 : 여성 30710명
20200422-22 : 여성 7130명
20200423-17 : 남성 15620명
20200423-20 : 여성 7470명
20200424-00 : 여성 12010명
20200424-21 : 남성 16890명
20200425-02 : 남성 11840명
20200425-02 : 여성 6970명
20200425-07 : 남성 5450명
20200425-15 : 남성 22520명
20200425-17 : 여성 21420명
20200425-20 : 여성 12810명
20200426-00 : 여성 9870명
20200426-04 : 여성 6820명
20200426-09 : 여성 12840명
2020

20200425-21 : 남성 15870명
20200426-14 : 여성 15780명
20200426-18 : 여성 8170명
20200426-20 : 남성 7560명
20200427-00 : 여성 11280명
20200427-01 : 남성 12420명
20200427-04 : 여성 11230명
20200427-06 : 여성 11510명
20200427-06 : 남성 17460명
20200428-00 : 여성 12860명
20200428-06 : 남성 17650명
20200428-11 : 남성 59790명
20200428-17 : 남성 51940명
20200428-18 : 남성 39130명
20200428-22 : 남성 13650명
20200429-21 : 여성 17090명
20200429-21 : 남성 21290명
20200430-05 : 남성 7560명
20200430-08 : 남성 10210명
20200430-21 : 여성 7130명
20200430-22 : 여성 11880명
20200401-05 : 남성 12790명
20200401-13 : 여성 39160명
20200401-16 : 여성 32750명
20200401-16 : 남성 55320명
20200402-10 : 여성 16430명
20200403-03 : 남성 11000명
20200403-13 : 여성 10670명
20200404-02 : 남성 11810명
20200404-12 : 여성 17380명
20200406-19 : 여성 17770명
20200406-21 : 남성 19520명
20200407-01 : 여성 11030명
20200407-02 : 남성 12910명
20200407-04 : 여성 8370명
20200407-16 : 여성 30420명
20200407-21 : 남성 13790명
20200408-00 : 여성 12210명
20200408-04 : 여성 7270명
20200408-07 : 여성 8350명
20200408-17 : 여성 39800명
20200408-21 : 남성 16120명